# SonarQube project configuration (partial)
# Ajusta la versión de Python que Sonar debe usar para análisis más precisos
sonar.projectKey=ISCOUTB_AS_SIAR-E
sonar.organization=isco-utb
sonar.projectName=AS_SIAR-E
sonar.projectVersion=1.0

# Fuentes y tests
sonar.sources=backend/app/
sonar.tests=backend/test/

# Exclusiones típicas
sonar.exclusions=**/.venv/**,**/venv/**,**/node_modules/**,**/__pycache__/**,infra/**,**/usr/local/**

sonar.python.version=3.11
sonar.python.coverage.reportPaths=coverage.xml

sonar.sourceEncoding=UTF-8
