# SonarQube project configuration (partial)
# Ajusta la versión de Python que Sonar debe usar para análisis más precisos
sonar.projectKey=AS_SIAR-E
sonar.projectName=AS_SIAR-E
sonar.sources=backend
sonar.python.version=3.11
sonar.python.coverage.reportPaths=coverage.xml
