name: SonarQube Scan
uses: sonarsource/sonarqube-scan-action@v4 # Prueba usando la v4 o v5 si la v6 te da problemas de compatibilidad
env:
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
with:
  args: >
    -Dsonar.organization=isco-utb
    -Dsonar.projectKey=ISCOUTB_AS_SIAR-E
    -Dsonar.python.coverage.reportPaths=coverage.xml
    -Dsonar.sources=backend/app
    -Dsonar.tests=backend/test